### PR TITLE
Completed objective a and b for Kevin

### PR DESCRIPTION
**Pull request by cassandraye**
* Cookie and I now understand how to use funtrp_sequence_struct_pick.py
* We were able to generate the top 100 windows for each hazard, additionally we created a function that remove windows with overlapping amino acid number n (defined as amino_overlap, currently set to 16)
* Additionally we also figured out how to generate the top 100 windows with 90% being the top toggle score while 10% are randomly sampled windows

### CODE REVIEW

**Review by dgretton — CHANGES_REQUESTED** [review]
Looking good. When we were on the call, we made a couple of cosmetic changes like a renamed variable and a few comments. could you add those and push please?

**Comment by dgretton** [comment]
> Looking good. When we were on the call, we made a couple of cosmetic changes like a renamed variable and a few comments. could you add those and push please?

@cassandraye @kaveriuberoy

**Comment by dgretton** [comment]
Am I right in thinking that most/all of these changes have been incorporated now that I've merged Cookie's pull request? @cassandraye

**Comment by kaveriuberoy** [comment]
Yes, I think so! I’ll just check it out and get back to you!

**Pull request closed without merging**
